version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/backend/command/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/backend/query/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/backend/read-model-updater/'
    schedule:
      interval: 'daily'
